### PR TITLE
fix array range violations

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Apparently the gcc-explorer framework dismisses empty lines upfront.
I found these while using it from the console.

**Comment by ibuclaw** [comment]
Thanks.

**Comment by ibuclaw** [comment]
By the way @MartinNowak - I wouldn't need these additional processing logic if dmd had the ability to compile to assembly.  _hint_ ;)

**Comment by MartinNowak** [comment]
Well, here is a disassembler https://github.com/MartinNowak/ngdb/blob/master/src/machine/x86dis.d, that's probably your best bet to get output from DMD ;).

**Pull request merged**
